export const BASE_URL='https://api.themoviedb.org'
export const TOKEN='eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwZDMxYzlkYTY0NmU4MmRmY2ZhYzFjOWVjMTU2ZDY4NyIsIm5iZiI6MTcyNzA2MzYzOC4wODM1MDcsInN1YiI6IjY2YTc0YTc1MDg1MDYzZTg3YTU2YzFjZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.quZ1CBMeOcgjtbCbM3pb18cizP-1gkWItWy3rjwWcRg'
export const IMG_URL='https://image.tmdb.org/t/p/original'